services:
  redis-db:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes --appendfsync everysec
    ports:
      - "6379:6379"
    volumes:
      - ./src/api_client/redis_data:/data
      
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - redis-db
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./.streamlit:/app/.streamlit
    environment:
      - REDIS_HOST=redis-db

