[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pubtrends"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "numpy>=2.2,<2.3",
    "streamlit==1.44.1",
    "pyarrow>=19,<20",
    "pandas>=2.2,<2.3",
    "plotly==6.0.1",
    "matplotlib>=3.10,<3.11",
    "redis>=5,<6",
    "aiohttp>=3.11,<4",
    "python-dotenv>=1,<2",
    "xmltodict==0.14.2",
    "nltk>=3.9,<4",
    "scikit-learn>=1.6,<1.7",
]

[project.optional-dependencies]
ci-packages = [
    "pytest",
    "pytest-asyncio",
    "pytest-custom_exit_code",
    "ruff"
]

[tool.ruff]
line-length = 120
target-version = "py311"

include = [
    "src/**/*.py",
    "tests/**/*.py"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "UP",
    "SIM",
    "C4",
]
ignore = [
    "E501"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
asyncio_mode = "auto"
markers = [
    "unit",
    "redis",
]
