[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pubtrends"
version = "0.1.0"
dependencies = [
    "numpy",
    "streamlit",
    "pyarrow<24.0.0",
    "pandas",
    "plotly",
    "matplotlib",
    "redis",
    "aiohttp",
    "python-dotenv",
    "xmltodict",
    "nltk",
    "scikit-learn",
]

[project.optional-dependencies]
ci_packages = [
    "pytest",
    "pytest-asyncio",
    "pytest-custom_exit_code",
    "ruff"
]

[tool.ruff]
line-length = 120
target-version = "py312"

include = [
    "src/**/*.py",
    "tests/**/*.py"
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "UP",
    "SIM",
    "C4",
]
ignore = [
    "E501"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
asyncio_mode = "auto"
markers = [
    "unit",
    "redis",
]
