name: 'Setup python environment'
description: 'Installing dependencies'

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      shell: bash
      run: |
        uv sync --extra ci-packages
        uv run python -m nltk.downloader stopwords
