name: Streamlit App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-python-env
      - name: Ruff linter
        run: |
          ruff check --output-format=github .
          ruff format --check .

  test-unit:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-python-env
      - name: Unit tests
        run: pytest tests/unit -m "unit" --suppress-no-test-exit-code

  test-redis:
    needs: lint
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      TEST_REDIS_HOST: localhost
      TEST_REDIS_PORT: 6379
      TEST_REDIS_DB: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-python-env
      - name: Redis tests
        run: pytest tests/integration -m "redis" --suppress-no-test-exit-code